### ISSUE TITLE
[Request] Option to copy "/lp applyedits" string without leading "/"

### ISSUE THREAD

**Issue by Bufhimat** [Turbotailz/LuckPermsWeb#34]
In console I type "lp editor", copy the result and open in the browser. I make my changes, and click the 'save' button in the top right corner, and am given a command to paste back into Minecraft to apply the changes, the command being "/lp applyedits" followed by a alphanumeric code.
I am working from the console, and when I go to paste the command I must move the cursor to the beginning of the line and delete the leading "/", or first copy the command into a text editor then into the console window.
I'm requesting a feature to remove the leading slash for easier copy-pasting directly into the console window and only need to press 'enter'. A button to click to remove before clicking to copy, or double clicking to copy without it are two possibilities.

**Comment by BrainStone** [comment]
I'm not suren where you want to track this @Turbotailz, so I'll reply this here.

I'm against this. For a variety of reasons:

1. The editor is meant as an easy to use tool. That includes very inexperiences server admins. Now they will paste whatever they are given. Meaning that if you give them a command without the slash they will paste it ingame and send it as chat. While that isn't the end of the world, it leaks information that isn't supposed to be public. If the slash remains the worst thing that can happen is that users can't just paste it in the console. And in that case no data is revealed, which is better
2. Sponge and Velocity handle slashes correctly. So this is an exclusive Spigot and Bungee issue. So while you'd convince some user you'd inconvience others
3. Continuing on the point, the effort to remove the slash manually or to add it manually is comparable (two keypresses (<kbd>Home</kbd>, <kbd>Del</kbd>) vs one (<kbd>BackSpace</kbd>)). So I'm not on board with the supposed benefit that change would bring. Also from experience pasting it in game is a lot more common than pasting it in the console, so the benefit essentially dissapears entirely.
4. It would break current behavior. I frankly think this is by far the biggest issue (not that my other points are irrelevant. I'd consider point 3 enough to not implement it, were it my project) is that this change would sublty change a behavior many people are used to. That will upset many admins as it's sooo easy to miss and will cause confusion when suddenly instead of applying your permissions you paste them in chat. It's a disruption to the workflow, that's just uncalled for.

As an alternative I was thinking about displaying both variants. However that also will cause a disruption of the workflow, as the position of the text box will most likely change. Also the second box will add confusion for inexperienced admins.

Now a real solution to this problem (besides pushing Spigot and BungeeCord to finally accept commands with leading slashes as well (like Sponge and Velocity does)) would be to implement hidden aliases of all LP commands with a leading slash. Hidden meaning they would never show in tab completion until the leading slash (or two slashes in-game) are typed.

**Comment by Andre601** [comment]
> I'm not suren where you want to track this @Turbotailz, so I'll reply this here.
> 
> I'm against this. For a variety of reasons:
> 
> 1. The editor is meant as an easy to use tool. That includes very inexperiences server admins. Now they will paste whatever they are given. Meaning that if you give them a command without the slash they will paste it ingame and send it as chat. While that isn't the end of the world, it leaks information that isn't supposed to be public. If the slash remains the worst thing that can happen is that users can't just paste it in the console. And in that case no data is revealed, which is better

Considering everyone can access the sata and that it won't affect the own server, is this a minor concern.
Just have a separate tab for the console command?
Like f.e. this:
- [ ] Console?

**Comment by Tobi406** [comment]
> 2. Sponge and Velocity handle slashes correctly. So this is an exclusive Spigot and Bungee issue. So while you'd convince some user you'd inconvience others

LuckPerms could just send what platform it is running on and then only display the console command if it is on a Bukkit or BungeeCord implementation. But that would also most likely confuse people that run any combination of servers where `/`s work and don't work.

**Comment by lucko** [comment]
The editor knows if the session was created from the console or by a player. Can just include a `/` if sent by a player, and not if sent by the console.

**Comment by BrainStone** [comment]
I'd be careful about changing the behavior of the editor based on where the command was executed. Like for example in my workflow I often switch between applying the edits from the console and ingame. I also open the editor interchangibly from in-game or the console. And I would find that change very very bothersome, as now I have to pay attention to what's in my clipboard instead of just deleting the first character every time I paste.

> Considering everyone can access the sata and that it won't affect the own server, is this a minor concern.
> Just have a separate tab for the console command?
> Like f.e. this:
>
> - [ ] Console?

I'd be against this, as this adds a click to the process, so nothing is gained. The only way that could be useful is if you store the state of the checkbox (maybe even in a cookie (but then we'd need a cookie policy).

Now one way to allow customizability and prevent inconsitencies in the behavior (trust me, inconsitent behavior has a much bigger impact on the work flow than a repetitive task) would be by having a config option. I could imagine it having 3 settings: ``slash``, ``noslash``, ``auto`` (slash or noslash depending on where the command was sent from). That would allow every admin to adjust it to their liking.
The default should be ``slash`` to keep the default behavior as it currently is.

Regardless I still think having those command aliases is the real solution, as in that case pasting the command as is will always work. There are no cases where it won't work. (Except you pasting the command in the wrong server (like opened the session on bungee and pasted in spigot console), but that's a different story)

**Comment by BrainStone** [comment]
Yay I win.
So anything from 5.0.135 will not care if you type a slash in the console or not for LP commands.
